import { sys_oper_log } from '@repo/database';
import { ADMIN_PREFIX } from 'src/modules/admin/admin.constants';
import { generatePageDto, generateDto, InfoDto } from 'src/common/utils/dto-generator';
export { ADMIN_PREFIX };
export const keyStr = '操作日志';
export const tableName = 'sys_oper_log';
export const controllerName = 'operlog';
export type tableType = sys_oper_log;
export const tableQueryType = generatePageDto(tableName);
export const tableDTO = generateDto(tableName);
export { InfoDto };
